# -*- coding: utf-8 -*-
"""Wordle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11tMK44nI4_LfHfEFnBLkFbJ_3USJltpc
"""

#códigos de colores:
#amarillo: \033[93m
#verde: \033[92m
#gris: \033[90mcr

#Se instalo una librería para escoger una palabra random
!pip install Faker
from faker import Faker
fake = Faker()
random_word = []
#Se establece que la palabra debe ser de 5 letras
while int(len(random_word)) != 5:
  random_word = fake.word()
  word = [letter for letter in random_word]

#Se crearon todas las variables que se utilizaran posteriormente
grey_letters = []
yellow_letters = []
green_letters = []
tries = 1
guess = ""
word_final = "".join(word)

#Esta función colorea cada una de las letras
def colored(guess):
  colored_guess = ""
  for letter in guess:
    if letter in green_letters:
       colored_guess += (f"\033[92m{letter}\033[0m")
    elif letter in yellow_letters:
       colored_guess += (f"\033[93m{letter}\033[0m")
    else:
      colored_guess += (f"\033[90m{letter}\033[0m")
  print (colored_guess)

#Las instrucciones del juego
print("Welcome to Wordle!")
print("Guess the world in 6 tries")
print("How to play?")
print("The green letters are part of the word and are in the correct spot")
print("The yellow letters are part of the word but are not in the correct spot")
print("The grey letters are not part of the word")
print("All your guesses must be 5-letter words")

#Se convierte el intento a una lista y se agrega cada letra a una lista dependiendo del color
#Tambien evalua si cada intento es el ganador
for i in range(6):
  while int(len(guess)) != 5:
    guess = [letra for letra in input()]
  if guess == word:
    print (f"\033[92m{guess}\033[0m")
    print (f"Congratulations it took you {tries} tries")
    break
  for letter in guess:
    if letter in word:
      if int(guess.index(letter)) == int(word.index(letter)):
        green_letters.append(letter)
      else:
        yellow_letters.append(letter)
    else:
      grey_letters.append(letter)
  tries += 1
  colored (guess)
  guess = ""
if guess != word:
  print (f"You are out of tries. The word was {word_final}")